name: Arrrrivals
description: A sample Polymer application
dependencies:
  polymer: ">=0.12.0 <0.13.0"
  core_elements: ">=0.1.0 <0.2.0"
  paper_elements: ">=0.1.0 <0.2.0"
transformers:
- polymer:
    entry_points: web/arrrrivals.html
- $dart2js:
    checked: true
    minify: false
    verbose: true
