name: Arrrrivals
description: A sample Polymer application
dependencies:
  core_elements: '>=0.1.0 <0.2.0'
  intl: any
  paper_elements: '>=0.1.0 <0.2.0'
  polymer: '>=0.12.0 <0.13.0'
transformers:
- polymer:
    entry_points: web/arrrrivals.html
