name: Arrrrivals
description: A sample Polymer application
dependencies:
  core_elements: any
  paper_elements: any
  polymer: any
transformers:
- $dart2js:
    checked: true
    minify: false
    verbose: true
- polymer:
    entry_points: 
        - web/arrrrivals.html
